#pragma once

#define  SIGCXX_MAJOR_VERSION 2 
#define SIGCXX_MINOR_VERSION 99 
#define SIGCXX_MICRO_VERSION 1 

//#define SIGCXX_API_VERSION 3.0 
//#define PACKAGE_VERSION ${ SIGCXX_MAJOR_VERSION }.${ SIGCXX_MINOR_VERSION }.${ SIGCXX_MICRO_VERSION } 
//#define LIBSIGCPP_SOVERSION 0 

