name: "CI: autotools: gcc 9"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker://ubuntu:19.10
    - name: Build
      run: |
        sudo apt update
        sudo apt install mm-common g++-9
        export CXX=g++-9
        ./autogen.sh
        ./configure
        make
    - name: Test
      run: make check
    - name: Distcheck
      run: make distcheck
